version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-3333}:3333"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DB_HOST=mysql
      - DB_PORT=${DB_PORT:-3306}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-easybroker123}
      - DB_DATABASE=${DB_DATABASE:-easybroker}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - easybroker-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-easybroker123}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-easybroker}
      MYSQL_USER: ${MYSQL_USER:-easybroker}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-easybroker123}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - easybroker-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: easybroker123
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - easybroker-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  easybroker-network:
    driver: bridge
